### ISSUE TITLE
建立新的发音评估时，报“SequelizeUniqueConstraintError” 错误

### ISSUE THREAD

**Issue by jadyyang** [ZuodaoTech/everyone-can-use-english#878]
在 “发音评估/新评估” 中自己录音，然后点击“确定”没有反应，控制台好像报了一个相关的错误：

```
Executing (default): SELECT `id`, `language`, `target_id` AS `targetId`, `target_type` AS `targetType`, `md5`, `filename`, `reference_id` AS `referenceId`, `reference_text` AS `referenceText`, `duration`, `synced_at` AS `syncedAt`, `uploaded_at` AS `uploadedAt`, `created_at` AS `createdAt`, `updated_at` AS `updatedAt` FROM `recordings` AS `Recording` WHERE `Recording`.`md5` = 'c1161b7b3df75384d10efc49ad5308ca';
Executing (default): INSERT INTO `recordings` (`id`,`target_id`,`md5`,`filename`,`reference_text`,`duration`,`created_at`,`updated_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8);
Error occurred in handler for 'recordings-create': Error
    at Database.<anonymous> (/Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.insert (/Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)
    at async Recording.save (/Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/model.js:2490:35)
    at async Recording.create (/Users/jadyyang/code/github/everyone-can-use-english/enjoy/node_modules/sequelize/lib/model.js:1362:12)
    at async create (file:///Users/jadyyang/code/github/everyone-can-use-english/enjoy/.vite/build/main-CuyASGz_.js:91488:23)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:83254) {
  name: 'SequelizeUniqueConstraintError',
  errors: [],
  parent: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: recordings.target_type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `recordings` (`id`,`target_id`,`md5`,`filename`,`reference_text`,`duration`,`created_at`,`updated_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8);'
  },
  original: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: recordings.target_type] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'INSERT INTO `recordings` (`id`,`target_id`,`md5`,`filename`,`reference_text`,`duration`,`created_at`,`updated_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8);'
  },
  fields: [],
  sql: 'INSERT INTO `recordings` (`id`,`target_id`,`md5`,`filename`,`reference_text`,`duration`,`created_at`,`updated_at`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8);'
}
```

**Comment by an-lee** [comment]
请问是上传了录音文件？还是在 Enjoy 上直接点的录音键录音？

**Comment by jadyyang** [comment]
在 Enjoy 上直接点的录音键录音

**Comment by an-lee** [comment]
找到原因了，我来改一下。
